const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const networkName = hre.network.name;
  console.log(`Starting deployment to ${networkName} testnet...\n`);

  const [deployer] = await hre.ethers.getSigners();
  console.log(`Deploying contracts with account: ${deployer.address}`);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log(`Account balance: ${hre.ethers.formatEther(balance)} ETH\n`);

  if (balance === 0n) {
    console.error("Error: Deployer account has 0 balance.");
    process.exit(1);
  }

  // 1. Deploy IdentityRegistry
  console.log("Deploying IdentityRegistry...");
  const IdentityRegistry = await hre.ethers.getContractFactory("IdentityRegistry");
  const identityRegistry = await IdentityRegistry.deploy(deployer.address);
  await identityRegistry.waitForDeployment();
  const irAddress = await identityRegistry.getAddress();
  console.log(`✅ IdentityRegistry deployed to: ${irAddress}`);

  // 2. Deploy Factory
  console.log("\nDeploying Factory...");
  const Factory = await hre.ethers.getContractFactory("Factory");
  const factory = await Factory.deploy(irAddress, deployer.address);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log(`✅ Factory deployed to: ${factoryAddress}`);

  // 3. Link Factory to IdentityRegistry
  console.log("\nLinking Factory to IdentityRegistry...");
  const tx = await identityRegistry.setFactory(factoryAddress);
  await tx.wait();
  console.log("✅ Factory address set in IdentityRegistry");

  // Save deployment addresses
  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentData = {
    network: networkName,
    chainId: hre.network.config.chainId,
    deployer: deployer.address,
    IdentityRegistry: irAddress,
    Factory: factoryAddress,
    timestamp: new Date().toISOString(),
  };

  const deploymentPath = path.join(deploymentsDir, `${networkName}.json`);
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentData, null, 2));
  console.log(`\nDeployment details saved to ${deploymentPath}`);

  // Save to frontend .env.[network]
  const envContent = `
# Auto-generated by deploy-testnet.js for ${networkName}
NEXT_PUBLIC_IDENTITY_REGISTRY_ADDRESS=${irAddress}
NEXT_PUBLIC_FACTORY_ADDRESS=${factoryAddress}
NEXT_PUBLIC_RPC_URL=${hre.network.config.url}
NEXT_PUBLIC_CHAIN_ID=${hre.network.config.chainId}
`;
  
  const envFile = networkName === 'localhost' ? '.env.local' : `.env.${networkName}`;
  const envPath = path.join(__dirname, "../../frontend", envFile);
  fs.writeFileSync(envPath, envContent.trim());
  console.log(`Frontend environment variables updated at frontend/${envFile}`);

  // Contract Verification
  console.log("\nWaiting for block confirmations before verification...");
  
  // Try to verify if it's not localhost
  if (networkName !== "localhost" && networkName !== "hardhat") {
    // Wait for 5 blocks for Etherscan to index
    console.log("Waiting for 5 block confirmations...");
    await factory.deploymentTransaction().wait(5);

    try {
      console.log("\nVerifying IdentityRegistry...");
      await hre.run("verify:verify", {
        address: irAddress,
        constructorArguments: [deployer.address],
      });

      console.log("\nVerifying Factory...");
      await hre.run("verify:verify", {
        address: factoryAddress,
        constructorArguments: [irAddress, deployer.address],
      });
      
      console.log("\n✅ All contracts verified successfully!");
    } catch (error) {
      console.error("\n❌ Contract verification failed:", error.message);
    }
  }

  console.log("\n🚀 Testnet deployment completed successfully!");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
