const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Starting local development setup...\n");

  const [owner, admin1, admin2, haUser, instUser, recipientUser] = await hre.ethers.getSigners();

  // 1. Deploy IdentityRegistry
  const IdentityRegistry = await hre.ethers.getContractFactory("IdentityRegistry");
  const identityRegistry = await IdentityRegistry.deploy(owner.address);
  await identityRegistry.waitForDeployment();
  const irAddress = await identityRegistry.getAddress();
  console.log(`IdentityRegistry deployed to: ${irAddress}`);

  // 2. Deploy Factory
  const Factory = await hre.ethers.getContractFactory("Factory");
  const factory = await Factory.deploy(irAddress, owner.address);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log(`Factory deployed to: ${factoryAddress}`);

  // 3. Link Factory to IdentityRegistry
  await identityRegistry.setFactory(factoryAddress);
  console.log("Factory address set in IdentityRegistry");

  // 4. Setup Admins (Need 3 total for HA approval)
  await identityRegistry.addAdmin(admin1.address);
  await identityRegistry.addAdmin(admin2.address);
  // owner is already an admin from constructor
  console.log("Added admin1 and admin2 to IdentityRegistry");

  // 5. Register & Approve Higher Authority
  const haName = "Global Accreditation Board";
  await identityRegistry.connect(haUser).registerHigherAuthority(haName);
  console.log(`\nHigher Authority '${haName}' registered by: ${haUser.address}`);

  await identityRegistry.connect(owner).approveHigherAuthority(haUser.address);
  await identityRegistry.connect(admin1).approveHigherAuthority(haUser.address);
  await identityRegistry.connect(admin2).approveHigherAuthority(haUser.address);
  console.log("Higher Authority approved by 3 admins");

  // 6. Register & Approve Institute
  const instName = "Tech University";
  await identityRegistry.connect(instUser).registerInstitute(instName, haUser.address);
  console.log(`\nInstitute '${instName}' registered by: ${instUser.address}`);

  await identityRegistry.connect(haUser).approveInstitute(instUser.address);
  console.log("Institute approved by Higher Authority");

  // Get the deployed Institute contract address
  const instContractAddr = await factory.getInstituteContract(instUser.address);
  console.log(`Institute Contract deployed at: ${instContractAddr}`);

  // Get Authority contract
  const haContractAddr = await factory.getAuthorityContract(haUser.address);
  console.log(`Authority Contract deployed at: ${haContractAddr}`);

  // 7. Purchase Credits for Institute
  const Institute = await hre.ethers.getContractFactory("Institute");
  const instContract = Institute.attach(instContractAddr);
  
  // Basic plan = 49 ether in contract
  await instContract.connect(instUser).purchaseCredits(1, { value: hre.ethers.parseEther("49") });
  console.log("Purchased 100 credits (Plan 1) for Institute");

  // 8. Submit Document Request
  const docHash = hre.ethers.keccak256(hre.ethers.toUtf8Bytes("Test Document Data"));
  await instContract.connect(instUser).submitDocumentRequest(docHash);
  console.log(`\nDocument request submitted with hash: ${docHash}`);

  // 9. Approve Document Request
  const Authority = await hre.ethers.getContractFactory("Authority");
  const haContract = Authority.attach(haContractAddr);
  await haContract.connect(haUser).approveDocumentRequest(haContractAddr, instUser.address, docHash);
  console.log("Document request approved by Higher Authority");

  // 10. Mint SBT
  await instContract.connect(instUser).mintSoulBoundToken(recipientUser.address, docHash);
  console.log(`SoulBound Token minted to: ${recipientUser.address}`);

  // 11. Write addresses to frontend .env.local
  const envContent = `
# Auto-generated by setup-dev.js
NEXT_PUBLIC_IDENTITY_REGISTRY_ADDRESS=${irAddress}
NEXT_PUBLIC_FACTORY_ADDRESS=${factoryAddress}
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545
NEXT_PUBLIC_CHAIN_ID=31337
`;

  const envPath = path.join(__dirname, "../../frontend/.env.local");
  fs.writeFileSync(envPath, envContent.trim());
  console.log(`\nAddresses written to ${envPath}`);

  // Print Summary
  console.log("\n=============================================");
  console.log("      LOCAL DEVELOPMENT ENVIRONMENT SUMMARY      ");
  console.log("=============================================");
  console.log(`Super Admin:       ${owner.address}`);
  console.log(`Admin 1:           ${admin1.address}`);
  console.log(`Admin 2:           ${admin2.address}`);
  console.log(`Higher Authority:  ${haUser.address}`);
  console.log(`Institute:         ${instUser.address}`);
  console.log(`SBT Recipient:     ${recipientUser.address}`);
  console.log("=============================================\n");
  console.log("You can import these accounts into MetaMask using the private keys from the Hardhat console.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
